TrajectoryPlannerROS:
 # robot configuration parameters
  max_vel_x: 1.0
  min_vel_x: -1.0
  max_vel_y: 1.0
  min_vel_y: -1.0
  max_vel_theta: 2.0
  min_in_place_vel_theta: 0.4

  acc_lim_theta: 3.2
  acc_lim_x: 2.5
  acc_lim_y: 2.5

  escape_vel: -0.2

  holonomic_robot: true
  y_vels: [-1.0, -0.1, 0.1, 1.0]

 # goal tolerance parameters
  yaw_goal_tolerance: 0.10
  xy_goal_tolerance: 0.10
  latch_xy_goal_tolerance: true

 # forward simulation parameters
  sim_time: 2.0
  sim_granularity: 0.025    # default = 0.025

 # trajectory scoring parameters
  pdist_scale: 0.4    # default = 0.6
  gdist_scale: 0.8    # default = 0.8
  
