DWAPlannerROS:
 # robot configuration parameters
  acc_lim_x: 2.5
  acc_lim_y: 2.5
  acc_lim_th: 3.2
  max_trans_vel: 1.0
  min_trans_vel: 0.1

  max_vel_x: 1.0
  min_vel_x: 0.1
  max_vel_y: 0.4
  min_vel_y: -0.4
  max_rot_vel: 1.57
  min_rot_vel: 0.79

 # goal tolerance parameters
  yaw_goal_tolerance: 0.10
  xy_goal_tolerance: 0.10
  latch_xy_goal_tolerance: false

 # forward simulation parameters
  sim_time: 0.4
  sim_granularity: 0.025    # default = 0.025

 # Trajectory scoring parameters
  stop_time_buffer: 0.4
   
  
