TrajectoryPlannerROS: # base_local_planner/TrajectoryPlannerROS
  max_vel_x: 0.30
  min_vel_x: 0.05
  max_vel_theta: 0.5
  min_in_place_vel_theta: 0.5
  holonomic_robot: true
  y_vels: [-0.30, -0.05, 0.05, 0.30]

  acc_lim_theta: 3.2
  acc_lim_x: 4
  acc_lim_y: 4

  yaw_goal_tolerance: 0.05
  xy_goal_tolerance: 0.1
  latch_xy_goal_tolerance: true
  prune_plan: true

  escape_vel: -0.1

  oscillation_timeout: 5
  oscillation_reset_dist: 0.1

  sim_time: 1.0
  sim_granularity: 0.05
  sim_granularity: 0.05
  vx_samples: 5
  vtheta_samples: 20

  controller_frequency: 10

  meter_scoring: true
  pdist_scale: 0.3
  gdist_scale: 0.6
  occdist_scale: 0.02
  heading_lookahead: 0.325
  heading_scoring: false
  heading_scoring_timestep: 0.8
  dwa: true
  publish_cost_grid_pc: true
