TrajectoryPlannerROS:
  max_vel_x: 0.30
  min_vel_x: 0.05
  max_vel_theta: 1.0
  min_in_place_vel_theta: 0.1
  y_vels: [-0.30, -0.05, 0.05, 0.30]

  acc_lim_theta: 3.2
  acc_lim_x: 4
  acc_lim_y: 4

  yaw_goal_tolerance: 0.05
  xy_goal_tolerance: 0.1
  latch_xy_goal_tolerance: true

  holonomic_robot: true

  oscillation_timeout: 5
