obstacle_range: 2.5
raytrace_range: 3.0
footprint: [[0.45, -0.35], [0.55, -0.1], [0.35, 0.3], [-0.32, 0.3], [-0.32, -0.3]]
footprint_padding: 0.00

cost_scaling_factor: 60
inflation_radius: 0.7
track_unknown_space: false

observation_sources: laser_scan_sensor rgbd_camera_sensor

laser_scan_sensor: {sensor_frame: front_hokuyo_link, data_type: LaserScan, topic: /scan, marking: true, clearing: true, inf_is_valid: false}
rgbd_camera_sensor: {sensor_frame: head_xtion_rgb_optical_frame, data_type: PointCloud, topic: /head_xtion/depth/points, marking: true, clearing: true, inf_is_valid: false}
