obstacle_range: 2.5
raytrace_range: 3.0
footprint: [[0.35, -0.30], [0.35, 0.30], [-0.35, 0.30], [-0.35, -0.30]]

inflation_radius: 0.55

observation_sources: laser_scan_sensor rgbd_camera_sensor

laser_scan_sensor: {sensor_frame: front_hokuyo_link, data_type: LaserScan, topic: /scan, marking: true, clearing: true, expected_update_rate: 32.0, inf_is_valid: false}

rgbd_camera_sensor: {sensor_frame: head_xtion_depth_optical_frame , data_type: PointCloud2, topic: /camera/depth_registered/points, marking: true, clearing: true, max_obstacle_height: 1.50, min_obstacle_height: 0.40}


