recovery_behaviors:
 - {name: conservative_reset, type: clear_costmap_recovery/ClearCostmapRecovery}
 - {name: rotate_recovery, type: rotate_recovery/RotateRecovery}
 - {name: aggressive_reset, type: clear_costmap_recovery/ClearCostmapRecovery}

controller_frequency: 10.0
  # The rate in Hz at which to run the control loop and send velocity commands to the base.

planner_patience: 1.0
  # How long the planner will wait in seconds in an attempt to find a valid plan before space-clearing operations are performed.

controller_patience: 2.0
  # How long the controller will wait in seconds without receiving a valid control before space-clearing operations are performed.

conservative_reset_dist: 0.1
  # The distance away from the robot in meters at which obstacles will be cleared from the costmap when attempting to clear space in the map. Note, this parameter is only used when the default recovery behaviors are used for move_base.

recovery_behavior_enabled: true
  # Whether or not to enable the move_base recovery behaviors to attempt to clear out space.

clearing_rotation_allowed: true
  # Determines whether or not the robot will attempt an in-place rotation when attempting to clear out space. Note: This parameter is only used when the default recovery behaviors are in use, meaning the user has not set the recovery_behaviors parameter to anything custom.

shutdown_costmaps: false
  # Determines whether or not to shutdown the costmaps of the node when move_base is in an inactive state

oscillation_timeout: 4.0
  # How long in seconds to allow for oscillation before executing recovery behaviors. A value of 0.0 corresponds to an infinite timeout. New in navigation 1.3.1

oscillation_distance: 0.5
  # How far in meters the robot must move to be considered not to be oscillating. Moving this far resets the timer counting up to the ~oscillation_timeout New in navigation 1.3.1

planner_frequency: 0.5
  # The rate in Hz at which to run the global planning loop. If the frequency is set to 0.0, the global planner will only run when a new goal is received or the local planner reports that its path is blocked. New in navigation 1.6.0

max_planning_retries: -1
  # How many times to allow for planning retries before executing recovery behaviors. A value of -1.0 corresponds to an infinite retries.

conservative_reset:
    reset_distance: 0.01
      # The radius away from the robot in meters outside which obstacles will be removed from the costmaps when they are reverted to the static map.

rotate_recovery:
  sim_granularity: 0.017
    # The distance in radians between checks for obstacles when checking if an in-place rotation is safe. Defaults to 1 degree.
  frequency: 10
    # The frequency in HZ at which to send velocity commands to the mobile base.

aggressive_reset:
    reset_distance: 0.01
      # The radius away from the robot in meters outside which obstacles will be removed from the costmaps when they are reverted to the static map.
