plugins: 
    - {name: static_map,          type: "costmap_2d::StaticLayer"}
    - {name: laser_observation,   type: "costmap_2d::ObstacleLayer"}
    - {name: camera_observation,  type: "costmap_2d::ObstacleLayer"}
    - {name: inflation_layer,     type: "costmap_2d::InflationLayer"}


publish_frequency: 1.0
laser_observation:
    observation_sources: base_scan
    base_scan:
        data_type: LaserScan
        sensor_frame: /front_hokuyo_link
        clearing: true
        marking: true
        topic: /scan

camera_observation:
    observation_sources: head_xtion
    head_xtion:
        data_type: PointCloud2
        sensor_frame: head_xtion_rgb_optical_frame
        clearing: true
        marking: true
        topic: /head_xtion/depth/points
    min_obstacle_height: 0.1
    max_obstacle_height: 2.0

inflation_layer:
    cost_scaling_factor: 60
    inflation_radius: 0.7


publish_frequency: 1.0


footprint: [[0.45, -0.35], [0.55, -0.1], [0.35, 0.3], [-0.32, 0.3], [-0.32, -0.3]]
footprint_padding: 0.00
