global_costmap:
  global_frame: map
  robot_base_frame: base_link
  update_frequency: 2.0
  publish_frequency: 2.0
  static_map: true
  rolling_window: false

  inflation_radius: 10.0
  footprint_padding: 0.05
  cost_scaling_factor: 5.0